# Get the Fast API image with Python version 3.7
FROM tiangolo/uvicorn-gunicorn-fastapi:python3.7

# Create the directory for the container
WORKDIR /app
COPY requirements.txt ./requirements.txt

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

COPY ./app.py ./

# Copy the serialized model and the vectors
COPY ./Models/model.pkl ./Models/model.pkl
COPY ./new_tfidf.pkl ./new_tfidf.pkl

# Run by specifying the host and port
CMD ["uvicorn", "app:app", "--host", "127.0.0.1", "--port", "10000"]